services:
  restaurant:
    image: mysql:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
